__title__ = 'pigeonML'
__description__ = 'Quickly annotate data in Jupyter.'
__url__ = 'https://github.com/dennisbakhuis/pigeonML'
__version__ = '0.2.0'
__author__ = 'Anastasis Germanidis, Dennis Bakhuis'
__author_email__ = 'agermanidis@gmail.com, dennis@bakhuis.nu'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2017 Anastasis Germanidis'
