"""Metadata of the package."""
__title__ = "pigeonXT"
__description__ = "Quickly annotate data in Jupyter."
__url__ = "https://github.com/dennisbakhuis/pigeonXT"
__version__ = "0.7.2"
__author__ = "Dennis Bakhuis"
__author_email__ = "pypi@bakhuis.nu"
__license__ = "Apache 2.0"
__copyright__ = "Copyright 2021 Dennis Bakhuis"
