__title__ = 'pigeonXT'
__description__ = 'Quickly annotate data in Jupyter.'
__url__ = 'https://github.com/dennisbakhuis/pigeonXT'
__version__ = '0.6.0'
__author__ = 'Dennis Bakhuis'
__author_email__ = 'dennis@bakhuis.nu'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2021 Dennis Bakhuis'
